[project]
name = "reminder-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbus-python>=1.3.2",
    "notify2>=0.3.1",
    "pynotify>=0.1.1",
    "pyqt5>=5.15.11",
]
